version: "3"

services:
  rootme_node:
    # You can use my own image, or build it from scratch
    image: ghcr.io/kernoeb/jean_racine_bot:main
#   build:
#     context: .
#     dockerfile: Dockerfile

    # Only if you want Tor nodes
    depends_on:
      tor-node-1:
        condition: service_healthy
      tor-node-2:
        condition: service_healthy
      tor-node-3:
        condition: service_healthy
      tor-node-4:
        condition: service_healthy
      tor-node-chall:
        condition: service_healthy
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - rootme
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    networks:
      - rootme
    ports:
      - "27017"
    volumes:
      - '/opt/jeanracine:/bitnami/mongodb'
  # Only if you want Tor nodes
  tor-node-1:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-2:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-3:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-4:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  tor-node-chall:
    image: osminogin/tor-simple
    networks:
      - rootme
    restart: always
  htmltoimage:
    image: ghcr.io/kernoeb/html_to_image:main
    restart: always
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:./docker/chrome.json

networks:
  rootme:
    driver: bridge
