version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - '/opt/jeanracine:/bitnami/mongodb'
  tor-node-1:
    image: osminogin/tor-simple
    ports:
      - "9050:9050"
    restart: always
  tor-node-2:
    image: osminogin/tor-simple
    ports:
      - "9051:9050"
    restart: always
  tor-node-3:
    image: osminogin/tor-simple
    ports:
      - "9052:9050"
    restart: always
  tor-node-4:
    image: osminogin/tor-simple
    ports:
      - "9053:9050"
    restart: always
  tor-node-5:
    image: osminogin/tor-simple
    ports:
      - "9054:9050"
    restart: always
  html-to-image:
    image: ghcr.io/kernoeb/html_to_image:main
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "11871:3000"
    security_opt:
      - seccomp:./docker/chrome.json

networks:
  rootme:
    driver: bridge
